all:
	make barber
	make smokers

barber:
	gcc --std=c99 -lpthread barberShop.c -o barberShop
smokers:
	gcc --std=c99 -lpthread smokingProblem.c -o smokingProblem
clean:
	rm barberShop
	rm smokingProblem
