concurrency2: concurrency2.c
	gcc --std=c99 -lpthread concurrency2.c -o concurrency2
concurrency3: concurrency3.c
	gcc --std=c99 -lpthread concurrency3.c -o concurrency3
countingSemaphore: countingSemaphore.c
	gcc --std=c99 -lpthread countingSemaphore.c -o countingSemaphore

clean:
	rm concurrency1 concurrency2 concurrency3 countingSemaphore
